### ISSUE TITLE
Orthography profile: "nd" as a single segment, vs "n d" in transnewguineaorg

### ISSUE THREAD

**Issue by XachaB** [lexibank/joophonosemantic#13] opened 2021-02-24 16:42 UTC
In this dataset, the sequence "nd" is segmented as a single segment:

https://github.com/lexibank/joophonosemantic/blob/master/etc/orthography.tsv#L192

Example: 

https://github.com/lexibank/joophonosemantic/blob/602f561d09d46639a4befdcd294059d00da4c336/cldf/forms.csv#L2897

However, the same sequence is segmented as "n d" in transnewguineaorg:

```
enga-wapi-one-1,164073,enga-wapi,one,mendai,mendai,m e n d a i,,davies_and_comrie1985,,,^ m e n d a i $,default
```

Is it possible to normalize to one or the other ?

**Comment by XachaB** [comment] 2021-03-02 11:41
pinging @LinguList

**Comment by LinguList** [comment] 2021-03-02 11:57
Look, @XachaB, this is not my idea, but the source, right? The source is already segmented. So you should bring this up in transnewguineaorg, where on eshould then discuss to merge all nd instances to prenasalized n + d, and the same for mb, ng, etc.! But here again, it should also be discussed with @SimonGreenhill.

**Comment by XachaB** [comment] 2021-03-02 12:05
Noted, thanks

**Comment by CMUgarte** [comment] 2024-08-02 15:15
I'm closing this since in transnewguineaorg the issue is already resolved.

**Closed as completed by CMUgarte** 2024-08-02 15:15 UTC
